- name: Install base packages
  yum: name={{ item }} state=installed
  with_items:
   - memcached
   - python-memcached
   - httpd
   - mod_wsgi

- name: Start memcached
  service: name={{ item }} state=started enabled=yes
  with_items:
   - memcached

