--- 

# MySQL Server hardening

- name: Change root password
  mysql_user: name=root host={{item}} password={{ mysql_root_password | mandatory }} state=present
  with_items:
    - '::1'
    - '127.0.0.1'
    - 'localhost'

- name: Create .my.cnf
  template:
   src: "client.my.cnf.j2"
   dest: "/root/.my.cnf"
   owner: root
   group: root
   mode: 0600

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE test
  changed_when: False
  ignore_errors: True

- name: Remove access to test database
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

# Repetition
- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Create database for Keystone
  mysql_db:
    name: keystone
    state: present

- name: Create user for Keystone DB
  mysql_user:
    name: keystone
    password: "{{ mysql_keystone_password | default('keystone') }}"
    priv: "keystone.*:ALL"
    host: "{{ item }}"
    state: present
  with_items:
    - '::1'
    - '127.0.0.1'
    - 'localhost'

